# An example GitHub Action for checking an Ada program

name: CI

# Trigger the action on pushes and PRs on the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Set up reviewdog
    - name: Setup reviewdog
      run: |
          mkdir -p $HOME/reviewdog/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/reviewdog/bin

    # Checkout the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Install the compiler
    - uses: ada-actions/toolchain@v0.1.0

    #########
    # BUILD #
    #########

    - name: Run gprbuild
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        status=0

        # Run gprbuild with
        #   *  -gnatef to print full path to source files
        #   *  2>&1 to capture stderr
        # in the || block, capture the exit status if nonzero
        gprbuild -v -Psdc -gnatef > output.txt 2>&1 || status=$?

        # Run the output through reviewdog, to decorate the PR
        cat output.txt | $HOME/reviewdog/bin/reviewdog -efm="%f:%l:%c: %m" -diff="git diff master" --reporter=github-pr-review

        # Check for errors
        if [ $status -ne 0 ]; then
           cat output.txt
           echo "ERROR: gprbuild returned $status"

           # This will cause the workflow to exit with $status
           bash -c "exit $status"
        fi

    #######################
    # COVERAGE USING GCOV #
    #######################

    - name: Run gprbuild with options needed by gcov
      run: |
         gprbuild -f -Psdc -cargs -ftest-coverage -fprofile-arcs -gnatws -largs -fprofile-generate
    
    - name: Run tests
      run: |
         obj/sdc < input.txt

    - name: Collect files
      run: |
        mkdir gcov_data
        for a in `find . -name "*.ad?"` ; do cp $a gcov_data/ ; done
        cp obj/*gc?? gcov_data/

    - name: Run gcov
      run: | 
         cd gcov_data
         gcov *.ad? 
         # Remove binder files
         rm b__*
         # Remove all gcov files that don't have a source present
         # (for instance gcov files generated for runtime units)
         for a in *.gcov ; do
            if [ ! -f ${a%%.gcov} ]; then
               rm $a
            fi
         done
         cd ..
        
    - name: Collect gcov data
      run: |
         touch coverage.txt
         for a in `ls gcov_data/*.gcov` ; do cat $a | sed -e "s%`pwd`/%%g" >> coverage.txt ; done
         cat coverage.txt

    - uses: codecov/codecov-action@v1
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: gcov_data/*.gcov
